version: '3'

services:
  app:
    build:
      context: .
      target: development-dependencies
    command: bun run dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
