services:
  app:
    build:
      context: .
      target: development-dependencies
    command: bun run dev -- --host 0.0.0.0
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5173
    tty: true
    stdin_open: true
