services:
  app:
    build:
      context: .
      target: development-dependencies
    command: bun run dev -- --host 0.0.0.0
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5173
    tty: true
    stdin_open: true

  storybook:
    build:
      context: .
      target: development-dependencies
    command: node ./.storybook/docker-start.js dev -p 6006 --host 0.0.0.0 --ci
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - STORYBOOK_DISABLE_TELEMETRY=1
      - CI=true
    tty: true
    stdin_open: true
