const Hero = () => {
  return (
    <div className="flex flex-col gap-6">
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>
      <p>Hero Page</p>

      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
      <button type="button">Button</button>
    </div>
  );
};

export default Hero;
